[package]
name = "gmailnator"
version = "0.1.0"
authors = ["Y0GAAAA <35837405+Y0GAAAA@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "1.5.1"
regex = "1.4.1"
lazy_static = "1.4.0"
url = "2.1.1"
scraper = "0.12.0"